### ISSUE TITLE
question: example anywhere?

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/node-piecemeta-apiclient#1]
This maybe?
https://github.com/PieceMeta/piecemeta-angular-frontend/blob/656e057fd74650a7f633ef5cc2c8b9f8b201eeec/src/shared/js/services/api.js

**Comment by dasantonym** [comment]
yes, thanks! as you can see from the broken node implementation this repo has been pretty much completely neglected... i'll add an example to the readme

**Comment by fjenett** [comment]
Here is roughly what i did …
https://gist.github.com/fjenett/66d85dd9a4270649a792
